// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/LiveControls.tsx";
import * as $$$0 from "./sections/Benefits.tsx";
import * as $$$1 from "./sections/GridCategory.tsx";
import * as $$$2 from "./sections/Head.tsx";
import * as $$$3 from "./sections/Home.tsx";
import * as $$$4 from "./sections/MattressSize.tsx";
import * as $$$5 from "./sections/TypesMattresses.tsx";
import * as $$$$0 from "./functions/LoadGitHubRaw.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: { "./islands/LiveControls.tsx": $$0 },
  sections: {
    "./sections/Benefits.tsx": $$$0,
    "./sections/GridCategory.tsx": $$$1,
    "./sections/Head.tsx": $$$2,
    "./sections/Home.tsx": $$$3,
    "./sections/MattressSize.tsx": $$$4,
    "./sections/TypesMattresses.tsx": $$$5,
  },
  functions: { "./functions/LoadGitHubRaw.ts": $$$$0 },
  schemas: {
    "./sections/Benefits.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/GridCategory.tsx": {
      "inputSchema": {
        "title": " Grid Category",
        "type": "object",
        "properties": {
          "gridItem": {
            "type": "array",
            "items": {
              "title": "GridCategoryProps",
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "link": {
                  "type": "string",
                  "title": "Link",
                },
                "imageMobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image Mobile",
                },
                "imageDesktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image Desktop",
                },
              },
              "required": [
                "title",
                "link",
                "imageMobile",
              ],
            },
            "title": "Grid Item",
          },
          "allCategories": {
            "type": "string",
            "title": "All Categories",
          },
        },
        "required": [
          "gridItem",
          "allCategories",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Head.tsx": {
      "inputSchema": {
        "title": " Head",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "url": {
            "type": "string",
            "title": "Url",
          },
          "imageUrl": {
            "type": "string",
            "title": "Image Url",
          },
          "faviconUrl": {
            "type": "string",
            "title": "Favicon Url",
          },
          "styleUrls": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Style Urls",
          },
          "themeColor": {
            "type": "string",
            "title": "Theme Color",
          },
        },
        "required": [
          "title",
          "description",
          "url",
          "imageUrl",
          "faviconUrl",
          "styleUrls",
          "themeColor",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Home.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/MattressSize.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/TypesMattresses.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./functions/LoadGitHubRaw.ts": {
      "inputSchema": {
        "title": " Load Git Hub Raw",
        "type": "object",
        "properties": {
          "repo": {
            "type": "string",
            "title": "Repo",
            "description": "Complete user/repo format",
          },
          "branch": {
            "type": "string",
            "title": "Branch",
            "description": "Branch",
          },
          "path": {
            "type": "string",
            "title": "Path",
            "description":
              "Path to fetch, or leave blank and add :path route param.",
          },
        },
        "required": [
          "repo",
          "branch",
          "path",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "5b1cd5713a375e18bb93e9635b8a2dc5fc2672cf",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
globalThis.manifest = manifest;

export default manifest;
